import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
// todo - import something for 

import { api } from "~/utils/api";
import { useEffect, useRef, useState } from "react";
import ReactMarkdown from "react-markdown";

const Home: NextPage = () => {
  const inputRef = useRef<HTMLInputElement>(null);
  const [inputValue, setInputValue] = useState<string>("");
  const hello = api.example.hello.useQuery({ text: inputValue }, {
    enabled: false,
  });
  const [messages, setMessages] = useState<string[]>([]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  }

  useEffect(() => {
    console.log("data changed");
    if (hello.data) {
      console.log(hello.data);
      setMessages(m => [...m, hello.data.greeting ?? "ERROR"]);
    }
  }, [hello.data]);

  const handleCopyClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    navigator.clipboard.writeText(e.currentTarget.previousSibling?.textContent ?? "");
  };

  return (
    <>
      <Head>
        <title>Chat T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex text-lg bg-slate-900 h-screen w-screen overflow-auto">
        <div className="fixed top-8 w-full">
          <input type="text" ref={inputRef} value={inputValue} onChange={handleInputChange}
            className="bg-transparent w-full border-b-2 border-white text-white focus:outline-none focus:border-blue-500 text-center"
          />
          <button onClick={(e) => {
            e.preventDefault();
            hello.refetch()
          }} className="bg-transparent border-2 border-white text-white px-4 py-2 rounded-md hover:bg-white hover:text-black">Send</button>
        </div>

        <div>
          {
            messages.map((m, i) => (
              <div key={i} className="text-white">
                <div style={{
                  color: "unset"
                }}
                  className="text-left"
                >
                  <ReactMarkdown>
                    {m}
                  </ReactMarkdown>

                </div>
                <button
                  onClick={handleCopyClick}
                  className="bg-transparent border-2 border-white text-white px-4 py-2 rounded-md hover:bg-white hover:text-black"
                >
                  copy
                </button>
                <button
                  onClick={(e) => {
                    e.preventDefault();
                    setMessages(m => m.filter((_, index) => index !== i));
                  }}
                  className="bg-transparent border-2 border-white text-white px-4 py-2 rounded-md hover:bg-white hover:text-black"
                >
                  x
                </button>
              </div>
            ))
          }
        </div>
      </main>
    </>
  );
};

export default Home;
